apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      run: nginx-deploy
  template:
    metadata:
      labels:
        run: nginx-deploy
    spec:
      containers:
      - image: yeonip/app:v1
        name: test
        ports:
        - containerPort: 80
  args:
    statusProcessors: "20"
    operationProcessors: "10"
    appResyncPeriod: "30"
